Acme\DemoBundle\Entity\Works:
    type: entity
    table: null
    repositoryClass: Acme\DemoBundle\Entity\WorksRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: string
            length: 255
    lifecycleCallbacks: {  }
